In [1]:
import numpy as np
import pandas as pd
float_formatter = "{:.2f}".format

np.set_printoptions(formatter={'float_kind':float_formatter})
#reading files into numpy
taxi=np.genfromtxt('/Users/saurabh/Documents/MLsets/nyc_taxis.csv',delimiter=',',skip_header=1)
#or taxi=taxi[1:]  to skip header
taxi_shape=taxi.shape

In [4]:
np.array([2,4,6,8]) + 10

array([12, 14, 16, 18])

In [5]:
np.array([2,4,6,8]) < 5

array([ True,  True, False, False])

In [7]:
a = np.array([1, 2, 3, 4, 5])
b = np.array(["blue", "blue", "red", "blue"])
c = np.array([80.0, 103.4, 96.9, 200.3])
print(a<3)
print(b=="blue")
print(c>100)

[ True  True False False False]
[ True  True False  True]
[False  True False  True]


In [2]:
taxi

array([[2016.00, 1.00, 1.00, ..., 11.65, 69.99, 1.00],
       [2016.00, 1.00, 1.00, ..., 8.00, 54.30, 1.00],
       [2016.00, 1.00, 1.00, ..., 0.00, 37.80, 2.00],
       ...,
       [2016.00, 6.00, 30.00, ..., 5.00, 63.34, 1.00],
       [2016.00, 6.00, 30.00, ..., 8.95, 44.75, 1.00],
       [2016.00, 6.00, 30.00, ..., 0.00, 54.84, 2.00]])

In [9]:
taxi_shape

(89560, 15)

In [16]:
pickup_month = taxi[:,1]

february_bool=pickup_month==2
february=pickup_month[february_bool]
february_rides=february.shape[0]
#boolean array must have the same length as the dimension you're indexing.

In [17]:
tip_amount = taxi[:,12]
tip_bool=tip_amount>50
top_tips=taxi[tip_bool,5:14]

In [18]:
top_tips

array([[4.00, 2.00, 21.45, 2004.00, 52.00, 0.80, 0.00, 52.80, 105.60],
       [3.00, 4.00, 9.20, 1041.00, 27.00, 1.30, 5.54, 60.00, 93.84],
       [2.00, 0.00, 19.80, 1671.00, 52.50, 1.30, 5.54, 59.34, 118.68],
       [4.00, 2.00, 18.42, 2968.00, 52.00, 0.80, 5.54, 80.00, 138.34],
       [3.00, 6.00, 0.49, 158.00, 3.50, 1.80, 0.00, 70.00, 75.30],
       [2.00, 2.00, 2.70, 381.00, 9.50, 0.80, 0.00, 60.00, 70.30],
       [3.00, 4.00, 9.54, 1210.00, 27.50, 0.80, 5.54, 55.00, 88.84],
       [2.00, 4.00, 17.60, 3251.00, 52.00, 0.80, 5.54, 65.00, 123.34],
       [4.00, 2.00, 38.20, 9252.00, 52.00, 0.80, 5.54, 80.00, 138.34],
       [4.00, 2.00, 18.00, 2276.00, 0.01, 0.30, 5.54, 62.00, 67.85],
       [2.00, 0.00, 26.21, 17029.00, 180.50, 0.80, 5.54, 100.00, 286.84],
       [2.00, 2.00, 0.00, 24.00, 2.50, 0.80, 0.00, 58.00, 61.30],
       [2.00, 1.00, 18.21, 3160.00, 55.50, 0.80, 0.00, 62.00, 118.30],
       [2.00, 2.00, 0.00, 3.00, 2.50, 1.80, 0.00, 75.70, 80.00],
       [2.00, 4.00, 18.68, 5

In [19]:
a = np.array(['red','blue','black','blue','purple'])
a[0] = 'orange'
print(a)

['orange' 'blue' 'black' 'blue' 'purple']


In [20]:
a[3:] = 'pink'
print(a)

['orange' 'blue' 'black' 'pink' 'pink']


In [21]:
ones = np.array([[1, 1, 1, 1, 1],
                 [1, 1, 1, 1, 1],
                 [1, 1, 1, 1, 1]])
ones[1,2] = 99
print(ones)

[[ 1  1  1  1  1]
 [ 1  1 99  1  1]
 [ 1  1  1  1  1]]


In [22]:
ones[0] = 42
print(ones)

[[42 42 42 42 42]
 [ 1  1 99  1  1]
 [ 1  1  1  1  1]]


In [23]:
ones[:,2] = 0
print(ones)

[[42 42  0 42 42]
 [ 1  1  0  1  1]
 [ 1  1  0  1  1]]


In [24]:
taxi_modified = taxi.copy()  #making a copy
taxi_modified[28214,5]=1   #value at 6th column and 28215 row changed to 1
taxi_modified[:,0]=16  #first column values changes to 16
taxi_modified[1800:1802,7]=taxi_modified[:,7].mean()   
# values for two rows replaced at 8th column with mean of entire column

In [25]:
a2 = np.array([1, 2, 3, 4, 5])
print(a2)
a2_bool = a2 > 2
print(a2_bool)

a2[a2_bool] = 99

print(a2)

[1 2 3 4 5]
[False False  True  True  True]
[ 1  2 99 99 99]


In [33]:
(taxi[taxi[:,6]==2]).shape[0]

11832

In [34]:
jfk=taxi[taxi[:,6]==2]
jfk_count=jfk.shape[0]
laguardia=taxi[taxi[:,6]==3]
laguardia_count=laguardia.shape[0]
newark=taxi[taxi[:,6]==5]
newark_count=newark.shape[0]

In [35]:
trip_mph = taxi[:,7] / (taxi[:,8] / 3600)
cleaned_taxi=taxi[trip_mph<100]
mean_distance=cleaned_taxi[:,7].mean()
mean_length=cleaned_taxi[:,8].mean()
mean_total_amount=cleaned_taxi[:,13].mean()
