In [1]:
import csv
import numpy as np

# import nyc_taxi.csv as a list of lists
f = open("/Users/saurabh/Documents/MLsets/nyc_taxis.csv", "r")
taxi_list = list(csv.reader(f))

# remove the header row
taxi_list = taxi_list[1:]

# convert all values to floats
converted_taxi_list = []
for row in taxi_list:
    converted_row = []
    for item in row:
        converted_row.append(float(item))
    converted_taxi_list.append(converted_row)

In [3]:
taxi=np.array(converted_taxi_list)

In [5]:
print(taxi)

[[2.016e+03 1.000e+00 1.000e+00 ... 1.165e+01 6.999e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 8.000e+00 5.430e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 0.000e+00 3.780e+01 2.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 5.000e+00 6.334e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 8.950e+00 4.475e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 0.000e+00 5.484e+01 2.000e+00]]


In [6]:
taxi.shape

(89560, 15)

In [8]:
taxi[2:]   #selects all rows starting from 2nd row

array([[2.016e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 3.780e+01,
        2.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 5.460e+00, 3.276e+01,
        1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 1.880e+01,
        2.000e+00],
       ...,
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 5.000e+00, 6.334e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 8.950e+00, 4.475e+01,
        1.000e+00],
       [2.016e+03, 6.000e+00, 3.000e+01, ..., 0.000e+00, 5.484e+01,
        2.000e+00]])

In [9]:
taxi[1:4]  #first three rows

array([[2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        1.000e+00, 1.629e+01, 1.520e+03, 4.500e+01, 1.300e+00, 0.000e+00,
        8.000e+00, 5.430e+01, 1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        6.000e+00, 1.270e+01, 1.462e+03, 3.650e+01, 1.300e+00, 0.000e+00,
        0.000e+00, 3.780e+01, 2.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
        6.000e+00, 8.700e+00, 1.210e+03, 2.600e+01, 1.300e+00, 0.000e+00,
        5.460e+00, 3.276e+01, 1.000e+00]])

In [13]:
taxi[1,3]  #select an item at first row and 3rd column

5.0

In [15]:
taxi[0]  #select first row

array([2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 0.000e+00, 2.000e+00,
       4.000e+00, 2.100e+01, 2.037e+03, 5.200e+01, 8.000e-01, 5.540e+00,
       1.165e+01, 6.999e+01, 1.000e+00])

In [20]:
taxi[:,0]  #selecting only first column

array([2016., 2016., 2016., ..., 2016., 2016., 2016.])

In [23]:
taxi[:,0:3]   #selecting first three columns at indices 0,1,2

array([[2.016e+03, 1.000e+00, 1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00],
       ...,
       [2.016e+03, 6.000e+00, 3.000e+01],
       [2.016e+03, 6.000e+00, 3.000e+01],
       [2.016e+03, 6.000e+00, 3.000e+01]])

In [24]:
cols=[1,3,4]

In [27]:
taxi[:,cols]   #selecting random columns

array([[1., 5., 0.],
       [1., 5., 0.],
       [1., 5., 0.],
       ...,
       [6., 4., 5.],
       [6., 4., 5.],
       [6., 4., 5.]])

In [28]:
taxi[2,1:4]  #columns at at indices 1,2,3 and row 2

array([1., 1., 5.])

In [31]:
taxi[1:,4]  #row indices 1 onwards at column indice 4

array([0., 0., 0., ..., 5., 5., 5.])

In [33]:
taxi[0:3,:3]  #first three rows and first three columns

array([[2.016e+03, 1.000e+00, 1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00]])

In [35]:
taxi.min(axis=1) #minimum of each row

array([0. , 0. , 0. , ..., 0.8, 0. , 0. ])

In [37]:
taxi.min(axis=0) #minimum of each column

array([ 2.016e+03,  1.000e+00,  1.000e+00,  1.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  1.000e+00, -5.200e+01,
       -1.800e+00, -5.540e+00,  0.000e+00, -5.834e+01,  1.000e+00])

In [39]:
taxi_5=taxi[:5]  #taking first 5 rows

In [42]:
taxi_con=taxi_5[:,9:13]  #columns from 9 to 12 inclusive

In [43]:
taxi_con

array([[52.  ,  0.8 ,  5.54, 11.65],
       [45.  ,  1.3 ,  0.  ,  8.  ],
       [36.5 ,  1.3 ,  0.  ,  0.  ],
       [26.  ,  1.3 ,  0.  ,  5.46],
       [17.5 ,  1.3 ,  0.  ,  0.  ]])