In [9]:
import numpy as np
import pandas as pd
from scipy import sparse

In [7]:
#creating a matrix
matrix=np.array([[1,2],[2,3],[3,4]])
matrix

array([[1, 2],
       [2, 3],
       [3, 4]])

In [14]:
matrix=np.array([[0,0],[0,1],[3,0]])
matrix_sparse=sparse.csr_matrix(matrix)
print(matrix_sparse)
#Sparse matrices only store nonzero elements and assume all other values will be zero, 
#leading to significant computational savings.Sparse matrices only 
#store nonzero elements and assume all other values will be zero, leading to significant computational savings.

  (1, 1)	1
  (2, 0)	3


There are a number of types of sparse matrices. However, in compressed sparse row (CSR) matrices, (1, 1) and (2, 0) represent the (zero-indexed) indices of the non- zero values 1 and 3, respectively.

In [15]:
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0,1,0,0,0,0,0,0,0,0],
[3,0,0,0,0,0,0,0,0,0]])

In [16]:
matrix_large_sparse = sparse.csr_matrix(matrix_large)

In [21]:
print(matrix_sparse,'\n'*2)
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3 


  (1, 1)	1
  (2, 0)	3


In [28]:
vector = np.array([1, 2, 3, 4, 5, 6])
vector

array([1, 2, 3, 4, 5, 6])

In [29]:
# Create matrix
matrix = np.array([[1, 2, 3], [4, 5, 6],
[7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
# Select third element of vector
vector[2]

3

In [25]:
# Select second row, second column
matrix[1,1]

5

In [34]:
vector

array([1, 2, 3, 4, 5, 6])

In [35]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [36]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [37]:
# Select everything after the third element
vector[3:]

array([4, 5, 6])

In [38]:
# Select the last element
vector[-1]

6

In [39]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
# Select all rows and the second column
matrix[:,1:2]


array([[2],
       [5],
       [8]])

In [42]:
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8],
[9, 10, 11, 12]])
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
# View number of rows and columns
matrix.shape

(3, 4)

In [44]:
# View number of elements (rows * columns)
matrix.size

12

In [45]:
# View number of dimensions
matrix.ndim

2

In [50]:
matrix = np.array([[1, 2, 3], [4, 5, 6],
[7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
# Create function that adds 100 to something
add_100 = lambda i: i + 100

In [48]:
# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)

In [51]:
# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [53]:
# Add 100 to all elements
matrix + 100 #broadcasting

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [54]:
np.max(matrix)

9

In [55]:
np.min(matrix)

1

In [56]:
# Find maximum element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [57]:
np.max(matrix, axis=1)

array([3, 6, 9])

In [58]:
# Return mean
np.mean(matrix)

5.0

In [61]:
# Return Variance
np.var(matrix)

6.666666666666667

In [62]:
# Return standard deviation
np.std(matrix)

2.581988897471611

In [65]:
# Find the mean value in each column
np.mean(matrix, axis=0)

array([4., 5., 6.])

In [70]:
#reshaping
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9],
[10, 11, 12]])
print(matrix,'\n')
# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)
#The only requirement is that the shape of the original and new matrix contain the same number of elements

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 



array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [76]:
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [77]:
# Transpose matrix
matrix.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [78]:
 # Transpose vector
np.array([1, 2, 3, 4, 5, 6]).T


array([1, 2, 3, 4, 5, 6])

In [79]:
# Tranpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [82]:
matrix = np.array([[1, 2, 3], [4, 5, 6],
[7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
matrix.flatten() #flatten is a simple method to transform a matrix into a one-dimensional array.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
# Return matrix rank
np.linalg.matrix_rank(matrix)

2

In [86]:
# Return determinant of matrix
np.linalg.det(matrix)

-9.51619735392994e-16

In [90]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
# Return diagonal elements
matrix.diagonal()

array([1, 5, 9])

In [92]:
# Return diagonal one above the main diagonal
matrix.diagonal(offset=1)

array([2, 6])

In [93]:
# Return diagonal one below the main diagonal
matrix.diagonal(offset=-1)

array([4, 8])

In [98]:
# Return trace
matrix.trace() 

15

In [99]:
sum(matrix.diagonal())

15

In [101]:
matrix = np.array([[1, -1, 3], [1, 1, 6],
[3, 8, 9]])
matrix

array([[ 1, -1,  3],
       [ 1,  1,  6],
       [ 3,  8,  9]])

In [102]:
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [103]:
# View eigenvalues
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [105]:
 # View eigenvectors
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

eigenvectors are vectors that, when that transformation is applied, change only in scale (not direction). More formally:
Av = λv
,where A is a square matrix, λ contains the eigenvalues and v contains the eigenvec‐ tors.

In [107]:
vector_a = np.array([1,2,3]) 
vector_b = np.array([4,5,6])

In [108]:
# Calculate dot product
np.dot(vector_a, vector_b)

32

In [110]:
matrix_a = np.array([[1, 1, 1], [1, 1, 1],
[1, 1, 2]])
matrix_b = np.array([[1, 3, 1], [1, 3, 1],
[1, 3, 8]])

In [111]:
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [112]:
# Subtract two matrices
np.subtract(matrix_a, matrix_b)


array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [113]:
# Add two matrices
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [114]:
 # Multiply two matrices
np.dot(matrix_a, matrix_b)

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [115]:
# Multiply two matrices element-wise
matrix_a * matrix_b

array([[ 1,  3,  1],
       [ 1,  3,  1],
       [ 1,  3, 16]])

In [116]:
 # Calculate inverse of matrix
np.linalg.inv(matrix)

array([[ 1.18181818e+00, -1.00000000e+00,  2.72727273e-01],
       [-2.72727273e-01,  1.51394049e-17,  9.09090909e-02],
       [-1.51515152e-01,  3.33333333e-01, -6.06060606e-02]])